//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeumannMozi_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edmNeumannMoziContainer : DbContext
    {
        public edmNeumannMoziContainer()
            : base("name=edmNeumannMoziContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Felhasznalo> FelhasznaloSet { get; set; }
        public virtual DbSet<Foglalas> FoglalasSet { get; set; }
        public virtual DbSet<Ules_foglalas> Ules_foglalasSet { get; set; }
        public virtual DbSet<Ules> UlesSet { get; set; }
        public virtual DbSet<Terem> TeremSet { get; set; }
        public virtual DbSet<Film> FilmSet { get; set; }
        public virtual DbSet<Vetites> VetitesSet { get; set; }
    }
}
