//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeumannMozi_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Vetites = new HashSet<Vetites>();
        }
    
        public int Id { get; set; }
        public string Cim { get; set; }
        public string Rendezo { get; set; }
        public string Szereplok { get; set; }
        public string Leiras { get; set; }
        public int Hossz { get; set; }
        public int Korhatar { get; set; }
        public string ElozetesLink { get; set; }
        public string ImdbLink { get; set; }
        public string PoszterLink { get; set; }
        public string Kategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vetites> Vetites { get; set; }
    }
}
