//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeumannMozi_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foglalas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Foglalas()
        {
            this.Ules_foglalas = new HashSet<Ules_foglalas>();
        }
    
        public int Id { get; set; }
        public bool Foglalt { get; set; }
        public bool FizetveVan { get; set; }
        public bool Aktiv { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<int> FelhasznaloId { get; set; }
    
        public virtual Felhasznalo Felhasznalo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ules_foglalas> Ules_foglalas { get; set; }
    }
}
