//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeumannMozi_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vetites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vetites()
        {
            this.Ules_foglalas = new HashSet<Ules_foglalas>();
        }
    
        public int Id { get; set; }
        public System.DateTime Kezdete { get; set; }
        public int TeremId { get; set; }
        public int FilmId { get; set; }
    
        public virtual Terem Terem { get; set; }
        public virtual Film Film { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ules_foglalas> Ules_foglalas { get; set; }
    }
}
